[package]
name = "launchpad"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "Apache 2.0"
# authors = ["Mirai Labs, LLC (contact@sm.xyz)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
launchpad = "0x0"
cascade_multisig = "0xde0053243f3226649701a7fe2c3988be11941bf3ff3535f3c8c5bf32fc600220"