[package]
name = "NexusLaunchpad"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Studio Mirai, LLC (contact@sm.xyz)"]

[dependencies]

[addresses]
nexus_launchpad = "0x0"
cascade_multisig = "0xde0053243f3226649701a7fe2c3988be11941bf3ff3535f3c8c5bf32fc600220"